### ISSUE TITLE
Unable to UE4 4.19 (zip & unzip)

### ISSUE THREAD

**Issue by marshal-it** [getnamo/ZipUtility-ue4#16] opened 2018-03-02 11:26 UTC
1.can build , but run PIE ,use zip function , will block in TaskGrphInterfaces.h-830..

**Comment by getnamo** [comment] 2018-03-10 14:04
Will investigate 4.19 when it gets released. I don't work with preview builds.

**Comment by getnamo** [comment] 2018-03-10 14:05
Kindly provide any logs you may have regarding this issue

**Comment by getnamo** [comment] 2018-03-18 14:28
seems to work without issue on my end, try the 4.19 pre-build found here: https://github.com/getnamo/ZipUtility-ue4/releases/tag/0.3.5 if that doesn't work, give more details on specifically breaking blueprints/code with examples

**Comment by getnamo** [comment] 2018-03-31 13:45
Closing due to 0.3.5 release. Re-open with specific logs/steps to reproduce errors if issue persists.

**Closed by getnamo** 2018-03-31 13:45 UTC
Labels: bug
